/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApplicationSAMLAllOfSpVerificationCertificates } from './applicationSAMLAllOfSpVerificationCertificates';

export class ApplicationSAMLAllOfSpVerification {
    'certificates'?: Array<ApplicationSAMLAllOfSpVerificationCertificates>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "certificates",
            "baseName": "certificates",
            "type": "Array<ApplicationSAMLAllOfSpVerificationCertificates>"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationSAMLAllOfSpVerification.attributeTypeMap;
    }
}

