/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApplicationResourceGrantApplication } from './applicationResourceGrantApplication';
import { ApplicationResourceGrantResource } from './applicationResourceGrantResource';
import { ApplicationResourceGrantScopes } from './applicationResourceGrantScopes';

export class ApplicationResourceGrant {
    'application'?: ApplicationResourceGrantApplication;
    /**
    * The time the resource was created.
    */
    'createdAt'?: string;
    /**
    * A string that specifies the application resource grant ID.
    */
    'id'?: string;
    'resource': ApplicationResourceGrantResource;
    'scopes': Array<ApplicationResourceGrantScopes>;
    /**
    * The time the resource was last updated.
    */
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "application",
            "baseName": "application",
            "type": "ApplicationResourceGrantApplication"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "resource",
            "baseName": "resource",
            "type": "ApplicationResourceGrantResource"
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "Array<ApplicationResourceGrantScopes>"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationResourceGrant.attributeTypeMap;
    }
}

