/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Environment } from './environment';
import { GroupMembership } from './groupMembership';
import { Population } from './population';
import { Role } from './role';
import { RoleAssignment } from './roleAssignment';
import { User } from './user';

export class EntityArrayEmbedded {
    'environments'?: Array<Environment>;
    'groupMemberships'?: Array<GroupMembership>;
    'populations'?: Array<Population>;
    'roleAssignments'?: Array<RoleAssignment>;
    'roles'?: Array<Role>;
    'users'?: Array<User>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "environments",
            "baseName": "environments",
            "type": "Array<Environment>"
        },
        {
            "name": "groupMemberships",
            "baseName": "groupMemberships",
            "type": "Array<GroupMembership>"
        },
        {
            "name": "populations",
            "baseName": "populations",
            "type": "Array<Population>"
        },
        {
            "name": "roleAssignments",
            "baseName": "roleAssignments",
            "type": "Array<RoleAssignment>"
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<Role>"
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<User>"
        }    ];

    static getAttributeTypeMap() {
        return EntityArrayEmbedded.attributeTypeMap;
    }
}

