/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GatewayLDAPAllOfNewUserLookupAttributeMappings } from './gatewayLDAPAllOfNewUserLookupAttributeMappings';
import { GatewayLDAPAllOfNewUserLookupPopulation } from './gatewayLDAPAllOfNewUserLookupPopulation';

/**
* (Optional) The configurations for initially authenticating new users who will be migrated to PingOne. Note If there are multiple users having the same user name, only the first user processed is provisioned.
*/
export class GatewayLDAPAllOfNewUserLookup {
    /**
    * A list of objects supplying a mapping of PingOne attributes to external LDAP attributes. One of the entries must be a mapping for \"username”. This is required for the PingOne user schema.
    */
    'attributeMappings': Array<GatewayLDAPAllOfNewUserLookupAttributeMappings>;
    /**
    * (Optional) The LDAP user search filter to use to match users against the entered user identifier at login. For example, (((uid=${identifier})(mail=${identifier})). Alternatively, this can be a search against the user directory.
    */
    'ldapFilterPattern'?: string;
    'population'?: GatewayLDAPAllOfNewUserLookupPopulation;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributeMappings",
            "baseName": "attributeMappings",
            "type": "Array<GatewayLDAPAllOfNewUserLookupAttributeMappings>"
        },
        {
            "name": "ldapFilterPattern",
            "baseName": "ldapFilterPattern",
            "type": "string"
        },
        {
            "name": "population",
            "baseName": "population",
            "type": "GatewayLDAPAllOfNewUserLookupPopulation"
        }    ];

    static getAttributeTypeMap() {
        return GatewayLDAPAllOfNewUserLookup.attributeTypeMap;
    }
}

