/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An object containing a users (int) property. This property lists the total number of users added to the group. You must use GET /environments/{envID}/groups with the include=totalMemberCounts query parameter to retrieve this property. This property is not returned with a list of groups.
*/
export class GroupTotalMemberCounts {
    /**
    * Number of users with direct membership
    */
    'users'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "users",
            "baseName": "users",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GroupTotalMemberCounts.attributeTypeMap;
    }
}

