/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ImageTargets {
    /**
    * A string that specifies the URL or fully qualified path to the image source file.
    */
    'href'?: string;
    /**
    * A string that specifies the UUID of the target image.
    */
    'id'?: string;
    /**
    * A string that specifies the type of format used for the image. Options are jpg, png, and gif.
    */
    'type'?: ImageTargets.TypeEnum;
    /**
    * The width of the image (in pixels).
    */
    'width'?: number;
    /**
    * The height of the image (in pixels).
    */
    'height'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ImageTargets.TypeEnum"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ImageTargets.attributeTypeMap;
    }
}

export namespace ImageTargets {
    export enum TypeEnum {
        Png = <any> 'PNG',
        Jpg = <any> 'JPG',
        Gif = <any> 'GIF'
    }
}
