/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MFAPushCredential } from './mFAPushCredential';
import { MFAPushCredentialAPNSAllOf } from './mFAPushCredentialAPNSAllOf';

export class MFAPushCredentialAPNS {
    /**
    * A string that specifies the type of the push credentials. Mandatory. Valid values APNS, FCM
    */
    'type': MFAPushCredentialAPNS.TypeEnum;
    /**
    * A string that Apple uses as an identifier to identify an authentication key.  Mandatory.
    */
    'key': string;
    /**
    * A string that Apple uses as an identifier to identify teams.
    */
    'teamId': string;
    /**
    * A string that Apple uses as the authentication token signing key to securely connect to APNS. This is a p8 file with a private key format.
    */
    'token': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "MFAPushCredentialAPNS.TypeEnum"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MFAPushCredentialAPNS.attributeTypeMap;
    }
}

export namespace MFAPushCredentialAPNS {
    export enum TypeEnum {
        Apns = <any> 'APNS',
        Fcm = <any> 'FCM'
    }
}
