/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RiskEvaluationResult {
    /**
    * A string that specifies the risk evaluation result type. Options are VALUE.
    */
    'type'?: RiskEvaluationResult.TypeEnum;
    /**
    * A string that specifies the risk evaluation result level. Options are HIGH, MEDIUM, and LOW.
    */
    'level'?: RiskEvaluationResult.LevelEnum;
    /**
    * A string that specifies any custom attribute the administrator defines.
    */
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "RiskEvaluationResult.TypeEnum"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "RiskEvaluationResult.LevelEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RiskEvaluationResult.attributeTypeMap;
    }
}

export namespace RiskEvaluationResult {
    export enum TypeEnum {
        Value = <any> 'VALUE'
    }
    export enum LevelEnum {
        High = <any> 'HIGH',
        Medium = <any> 'MEDIUM',
        Low = <any> 'LOW'
    }
}
