/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RiskEvaluationEventEvaluatedFactors {
    /**
    * A string that specifies the state of the transaction. Options are FAILED, IN_PROGRESS, and SUCCESS.
    */
    'status'?: RiskEvaluationEventEvaluatedFactors.StatusEnum;
    /**
    * A string that specifies the transaction type.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "RiskEvaluationEventEvaluatedFactors.StatusEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RiskEvaluationEventEvaluatedFactors.attributeTypeMap;
    }
}

export namespace RiskEvaluationEventEvaluatedFactors {
    export enum StatusEnum {
        Failed = <any> 'FAILED',
        InProgress = <any> 'IN_PROGRESS',
        Success = <any> 'SUCCESS'
    }
}
