/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectEnvironment } from './objectEnvironment';
import { RiskEvaluationDetails } from './riskEvaluationDetails';
import { RiskEvaluationEvent } from './riskEvaluationEvent';
import { RiskEvaluationResult } from './riskEvaluationResult';
import { RiskEvaluationRiskPolicySet } from './riskEvaluationRiskPolicySet';

export class RiskEvaluation {
    /**
    * The time the resource was created (format ISO-8061).
    */
    'createdAt'?: string;
    'details'?: RiskEvaluationDetails;
    'environment'?: ObjectEnvironment;
    'event': RiskEvaluationEvent;
    /**
    * A string that specifies the resource’s unique identifier.
    */
    'id'?: string;
    'riskPolicySet'?: RiskEvaluationRiskPolicySet;
    'result'?: RiskEvaluationResult;
    /**
    * The time the resource was last updated (format ISO-8061).
    */
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "RiskEvaluationDetails"
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "ObjectEnvironment"
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "RiskEvaluationEvent"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "riskPolicySet",
            "baseName": "riskPolicySet",
            "type": "RiskEvaluationRiskPolicySet"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "RiskEvaluationResult"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RiskEvaluation.attributeTypeMap;
    }
}

