/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RiskPredictorDefault } from './riskPredictorDefault';
import { RiskPredictorMap } from './riskPredictorMap';

export class RiskPredictor {
    /**
    * A string that specifies the resource’s unique identifier.
    */
    'id'?: string;
    /**
    * A string type. A unique, friendly name for the predictor. This name is displayed in the Risk Policies UI, when the admin is asked to define the overrides and weights.
    */
    'name'?: string;
    /**
    * A string type. A unique name for the predictor. This property is immutable; it cannot be modified after initial creation. The value must be alpha-numeric, with no special characters or spaces. This name is used in the API both for policy configuration, and in the Risk Evaluation response (under details).
    */
    'compactName'?: string;
    /**
    * An enum type. This can be either VELOCITY, USER_RISK_BEHAVIOR, or MAP
    */
    'type'?: RiskPredictor.TypeEnum;
    /**
    * A string type. This specifies the desription of the risk predictor. Maximum length is 1024 characters.
    */
    'description'?: string;
    /**
    * The time the resource was created.
    */
    'createdAt'?: string;
    /**
    * The time the resource was updated.
    */
    'updatedAt'?: string;
    '_default'?: RiskPredictorDefault;
    'map'?: RiskPredictorMap;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "compactName",
            "baseName": "compactName",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RiskPredictor.TypeEnum"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "RiskPredictorDefault"
        },
        {
            "name": "map",
            "baseName": "map",
            "type": "RiskPredictorMap"
        }    ];

    static getAttributeTypeMap() {
        return RiskPredictor.attributeTypeMap;
    }
}

export namespace RiskPredictor {
    export enum TypeEnum {
        Velocity = <any> 'VELOCITY',
        UserRiskBehavior = <any> 'USER_RISK_BEHAVIOR',
        Map = <any> 'MAP'
    }
}
