/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An object that specifies the browser fingerprint attributes. Browser data can be retrieved using browser fingerprint JS. For more information, see Overview of the PingOne Risk Integration Kit.
*/
export class RiskEvaluationEventBrowser {
    'userAgent'?: string;
    'cookie'?: string;
    'language'?: string;
    'colorDepth'?: number;
    'deviceMemory'?: number;
    'hardwareConcurrency'?: number;
    'screenResolution'?: Array<number>;
    'availableScreenResolution'?: Array<number>;
    'timezoneOffset'?: number;
    'timezone'?: string;
    'sessionStorage'?: boolean;
    'localStorage'?: boolean;
    'indexedDb'?: boolean;
    'addBehaviour'?: object;
    'openDatabase'?: boolean;
    'cpuClass'?: string;
    'platform'?: string;
    'plugins'?: Array<object>;
    'webglVendorAndRenderer'?: string;
    'webgl'?: Array<string>;
    'adBlock'?: boolean;
    'hasLiedLanguages'?: boolean;
    'hasLiedResolution'?: boolean;
    'hasLiedOs'?: boolean;
    'hasLiedBrowser'?: boolean;
    'touchSupport'?: Array<string>;
    'fonts'?: Array<string>;
    'audio'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userAgent",
            "baseName": "userAgent",
            "type": "string"
        },
        {
            "name": "cookie",
            "baseName": "cookie",
            "type": "string"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string"
        },
        {
            "name": "colorDepth",
            "baseName": "colorDepth",
            "type": "number"
        },
        {
            "name": "deviceMemory",
            "baseName": "deviceMemory",
            "type": "number"
        },
        {
            "name": "hardwareConcurrency",
            "baseName": "hardwareConcurrency",
            "type": "number"
        },
        {
            "name": "screenResolution",
            "baseName": "screenResolution",
            "type": "Array<number>"
        },
        {
            "name": "availableScreenResolution",
            "baseName": "availableScreenResolution",
            "type": "Array<number>"
        },
        {
            "name": "timezoneOffset",
            "baseName": "timezoneOffset",
            "type": "number"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string"
        },
        {
            "name": "sessionStorage",
            "baseName": "sessionStorage",
            "type": "boolean"
        },
        {
            "name": "localStorage",
            "baseName": "localStorage",
            "type": "boolean"
        },
        {
            "name": "indexedDb",
            "baseName": "indexedDb",
            "type": "boolean"
        },
        {
            "name": "addBehaviour",
            "baseName": "addBehaviour",
            "type": "object"
        },
        {
            "name": "openDatabase",
            "baseName": "openDatabase",
            "type": "boolean"
        },
        {
            "name": "cpuClass",
            "baseName": "cpuClass",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string"
        },
        {
            "name": "plugins",
            "baseName": "plugins",
            "type": "Array<object>"
        },
        {
            "name": "webglVendorAndRenderer",
            "baseName": "webglVendorAndRenderer",
            "type": "string"
        },
        {
            "name": "webgl",
            "baseName": "webgl",
            "type": "Array<string>"
        },
        {
            "name": "adBlock",
            "baseName": "adBlock",
            "type": "boolean"
        },
        {
            "name": "hasLiedLanguages",
            "baseName": "hasLiedLanguages",
            "type": "boolean"
        },
        {
            "name": "hasLiedResolution",
            "baseName": "hasLiedResolution",
            "type": "boolean"
        },
        {
            "name": "hasLiedOs",
            "baseName": "hasLiedOs",
            "type": "boolean"
        },
        {
            "name": "hasLiedBrowser",
            "baseName": "hasLiedBrowser",
            "type": "boolean"
        },
        {
            "name": "touchSupport",
            "baseName": "touchSupport",
            "type": "Array<string>"
        },
        {
            "name": "fonts",
            "baseName": "fonts",
            "type": "Array<string>"
        },
        {
            "name": "audio",
            "baseName": "audio",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RiskEvaluationEventBrowser.attributeTypeMap;
    }
}

