/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RiskEvaluationEventBrowser } from './riskEvaluationEventBrowser';
import { RiskEvaluationEventEvaluatedFactors } from './riskEvaluationEventEvaluatedFactors';
import { RiskEvaluationEventFlow } from './riskEvaluationEventFlow';
import { RiskEvaluationEventSession } from './riskEvaluationEventSession';
import { RiskEvaluationEventTargetResource } from './riskEvaluationEventTargetResource';
import { RiskEvaluationEventUser } from './riskEvaluationEventUser';

export class RiskEvaluationEvent {
    'browser'?: RiskEvaluationEventBrowser;
    /**
    * A string that specifies the state of the transaction. Options are FAILED, IN_PROGRESS, and SUCCESS. If a value is not provided, the value defaults to IN_PROGRESS. The value of this property can be changed only if its current state is IN_PROGRESS.
    */
    'completionStatus'?: RiskEvaluationEvent.CompletionStatusEnum;
    'evaluatedFactors'?: RiskEvaluationEventEvaluatedFactors;
    /**
    * A string that specifies the origin IP address of the authentication flow. This is a required property.
    */
    'ip'?: string;
    'flow'?: RiskEvaluationEventFlow;
    /**
    * A string that specifies the calling service.
    */
    'origin'?: string;
    'session'?: RiskEvaluationEventSession;
    'targetResource'?: RiskEvaluationEventTargetResource;
    'user'?: RiskEvaluationEventUser;
    /**
    * A string that specifies the device sharing type. Options are UNSPECIFIED, SHARED, and PRIVATE.
    */
    'sharingType'?: RiskEvaluationEvent.SharingTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "browser",
            "baseName": "browser",
            "type": "RiskEvaluationEventBrowser"
        },
        {
            "name": "completionStatus",
            "baseName": "completionStatus",
            "type": "RiskEvaluationEvent.CompletionStatusEnum"
        },
        {
            "name": "evaluatedFactors",
            "baseName": "evaluatedFactors",
            "type": "RiskEvaluationEventEvaluatedFactors"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "flow",
            "baseName": "flow",
            "type": "RiskEvaluationEventFlow"
        },
        {
            "name": "origin",
            "baseName": "origin",
            "type": "string"
        },
        {
            "name": "session",
            "baseName": "session",
            "type": "RiskEvaluationEventSession"
        },
        {
            "name": "targetResource",
            "baseName": "targetResource",
            "type": "RiskEvaluationEventTargetResource"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "RiskEvaluationEventUser"
        },
        {
            "name": "sharingType",
            "baseName": "sharingType",
            "type": "RiskEvaluationEvent.SharingTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return RiskEvaluationEvent.attributeTypeMap;
    }
}

export namespace RiskEvaluationEvent {
    export enum CompletionStatusEnum {
        Failed = <any> 'FAILED',
        InProgress = <any> 'IN_PROGRESS',
        Success = <any> 'SUCCESS'
    }
    export enum SharingTypeEnum {
        Unspecified = <any> 'UNSPECIFIED',
        Shared = <any> 'SHARED',
        Private = <any> 'PRIVATE'
    }
}
