/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RiskEvaluationDetailsPreviousSuccessfulTransaction {
    /**
    * A boolean that specifies whether an anonymous network was detected. Information is available twenty-four hours after the last successful transaction.
    */
    'anonymousNetworkDetected'?: boolean;
    /**
    * A string that specifies the country of the IP address involved in the transaction. Information is available twenty-four hours after the last successful transaction.
    */
    'country'?: string;
    /**
    * A string that specifies the state of the IP address involved in the transaction. Information is available twenty-four hours after the last successful transaction.
    */
    'state'?: string;
    /**
    * A string that specifies the city of the IP address involved in the transaction. Information is available twenty-four hours after the last successful transaction.
    */
    'city'?: string;
    /**
    * A string that specifies the IP address involved in the transaction. Information is available twenty-four hours after the last successful transaction.
    */
    'ip'?: string;
    /**
    * A date that specifies the timestamp of the transaction. Information is available twenty-four hours after the last successful transaction.
    */
    'timestamp'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "anonymousNetworkDetected",
            "baseName": "anonymousNetworkDetected",
            "type": "boolean"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RiskEvaluationDetailsPreviousSuccessfulTransaction.attributeTypeMap;
    }
}

