/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RiskEvaluationDetailsUserVelocityByIpThreshold } from './riskEvaluationDetailsUserVelocityByIpThreshold';
import { RiskEvaluationDetailsUserVelocityByIpVelocity } from './riskEvaluationDetailsUserVelocityByIpVelocity';

export class RiskEvaluationDetailsUserVelocityByIp {
    /**
    * An enum indicating whether the calculated number of users per IP is LOW, MEDIUM, or HIGH.
    */
    'level'?: RiskEvaluationDetailsUserVelocityByIp.LevelEnum;
    /**
    * A string indicating the reason the user was flagged. For example \"More than 250 users accessed IP address 1.1.1.1 during the last 1 hour.\"
    */
    'reason'?: string;
    'threshold'?: RiskEvaluationDetailsUserVelocityByIpThreshold;
    'velocity'?: RiskEvaluationDetailsUserVelocityByIpVelocity;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "level",
            "baseName": "level",
            "type": "RiskEvaluationDetailsUserVelocityByIp.LevelEnum"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        },
        {
            "name": "threshold",
            "baseName": "threshold",
            "type": "RiskEvaluationDetailsUserVelocityByIpThreshold"
        },
        {
            "name": "velocity",
            "baseName": "velocity",
            "type": "RiskEvaluationDetailsUserVelocityByIpVelocity"
        }    ];

    static getAttributeTypeMap() {
        return RiskEvaluationDetailsUserVelocityByIp.attributeTypeMap;
    }
}

export namespace RiskEvaluationDetailsUserVelocityByIp {
    export enum LevelEnum {
        Low = <any> 'LOW',
        Medium = <any> 'MEDIUM',
        High = <any> 'HIGH'
    }
}
