/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectEnvironment } from './objectEnvironment';
import { RiskPolicyResult } from './riskPolicyResult';
import { RiskPolicySetRiskPolicies } from './riskPolicySetRiskPolicies';

export class RiskPolicySet {
    /**
    * The time the resource was created (format ISO-8061).
    */
    'createdAt'?: string;
    /**
    * A boolean that specifies whether this risk policy set is the environment\'s default risk policy set, which is used whenever an explicit policySet ID is not specified in the risk policy evaluation request. If this property is not specified, the value defaults to false, and this risk policy set is not regarded as the default risk policy set for the environment. When this property is set to true (in PUT or POST requests), the default property of all other risk policy sets in the environment is set to false.
    */
    '_default'?: boolean;
    'defaultResult'?: RiskPolicyResult;
    /**
    * A string that specifies a description for this policy set. This is an optional property. Valid characters consist of any Unicode letter, mark (for example, accent, umlaut), numeric character, punctuation character, or space. Maximum size is 1024 characters.
    */
    'description'?: string;
    'environment'?: ObjectEnvironment;
    /**
    * A string that specifies the resource’s unique identifier.
    */
    'id'?: string;
    /**
    * A string that specifies a name for this policy set. Valid characters consist of any Unicode letter, mark (for example, accent, umlaut), numeric character, forward slash, dot, apostrophe, underscore, space, or hyphen. Maximum size is 256 characters.
    */
    'name': string;
    /**
    * An array of policies related to this policy set.
    */
    'riskPolicies'?: Array<RiskPolicySetRiskPolicies>;
    /**
    * The time the resource was last updated (format ISO-8061).
    */
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean"
        },
        {
            "name": "defaultResult",
            "baseName": "defaultResult",
            "type": "RiskPolicyResult"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "ObjectEnvironment"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "riskPolicies",
            "baseName": "riskPolicies",
            "type": "Array<RiskPolicySetRiskPolicies>"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RiskPolicySet.attributeTypeMap;
    }
}

