/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RoleAssignmentScope {
    /**
    * A string that specifies the role assignment scope ID.
    */
    'id': string;
    /**
    * A string that specifies the type of resource defining the scope of the Role assignment. Options are ORGANIZATION, ENVIRONMENT, and POPULATION.
    */
    'type': RoleAssignmentScope.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RoleAssignmentScope.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return RoleAssignmentScope.attributeTypeMap;
    }
}

export namespace RoleAssignmentScope {
    export enum TypeEnum {
        Organization = <any> 'ORGANIZATION',
        Environment = <any> 'ENVIRONMENT',
        Population = <any> 'POPULATION'
    }
}
