/**
 * PingOne Platform API - Management
 * A bare-bones collection for the PingOne API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserPasswordExternalGatewayUserType } from './userPasswordExternalGatewayUserType';

/**
* (Optional) An object containing the gateway properties. When this is value is specified, the user’s password is managed in an external directory. You can set the user password using Create User (Import) or Update Password (Set).
*/
export class UserPasswordExternalGateway {
    /**
    * The UUID of the linked gateway that references the remote directory.
    */
    'id'?: string;
    /**
    * An enum indicating one of the supported gateway types. For the supported types, see type in the Gateway base data model.
    */
    'type'?: string;
    'userType'?: UserPasswordExternalGatewayUserType;
    /**
    * An object that maps the external LDAP directory attributes to PingOne attributes. We use the correlationAttributes values to read the attributes from the external LDAP directory and map them to the corresponding PingOne attributes.
    */
    'correlationAttributes'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "userType",
            "baseName": "userType",
            "type": "UserPasswordExternalGatewayUserType"
        },
        {
            "name": "correlationAttributes",
            "baseName": "correlationAttributes",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return UserPasswordExternalGateway.attributeTypeMap;
    }
}

