export * from './managementAPIsActiveIdentityCountsApi';
import { ManagementAPIsActiveIdentityCountsApi } from './managementAPIsActiveIdentityCountsApi';
export * from './managementAPIsAgreementManagementAgreementLanguagesResourcesApi';
import { ManagementAPIsAgreementManagementAgreementLanguagesResourcesApi } from './managementAPIsAgreementManagementAgreementLanguagesResourcesApi';
export * from './managementAPIsAgreementManagementAgreementRevisionsResourcesApi';
import { ManagementAPIsAgreementManagementAgreementRevisionsResourcesApi } from './managementAPIsAgreementManagementAgreementRevisionsResourcesApi';
export * from './managementAPIsAgreementManagementAgreementsResourcesApi';
import { ManagementAPIsAgreementManagementAgreementsResourcesApi } from './managementAPIsAgreementManagementAgreementsResourcesApi';
export * from './managementAPIsAlertingApi';
import { ManagementAPIsAlertingApi } from './managementAPIsAlertingApi';
export * from './managementAPIsApplicationsApplicationAttributeMappingApi';
import { ManagementAPIsApplicationsApplicationAttributeMappingApi } from './managementAPIsApplicationsApplicationAttributeMappingApi';
export * from './managementAPIsApplicationsApplicationMFAPushCredentialsApi';
import { ManagementAPIsApplicationsApplicationMFAPushCredentialsApi } from './managementAPIsApplicationsApplicationMFAPushCredentialsApi';
export * from './managementAPIsApplicationsApplicationResourceGrantsApi';
import { ManagementAPIsApplicationsApplicationResourceGrantsApi } from './managementAPIsApplicationsApplicationResourceGrantsApi';
export * from './managementAPIsApplicationsApplicationRoleAssignmentsApi';
import { ManagementAPIsApplicationsApplicationRoleAssignmentsApi } from './managementAPIsApplicationsApplicationRoleAssignmentsApi';
export * from './managementAPIsApplicationsApplicationSecretApi';
import { ManagementAPIsApplicationsApplicationSecretApi } from './managementAPIsApplicationsApplicationSecretApi';
export * from './managementAPIsApplicationsApplicationSignOnPolicyAssignmentsApi';
import { ManagementAPIsApplicationsApplicationSignOnPolicyAssignmentsApi } from './managementAPIsApplicationsApplicationSignOnPolicyAssignmentsApi';
export * from './managementAPIsApplicationsApplicationsApi';
import { ManagementAPIsApplicationsApplicationsApi } from './managementAPIsApplicationsApplicationsApi';
export * from './managementAPIsAuditActivitiesApi';
import { ManagementAPIsAuditActivitiesApi } from './managementAPIsAuditActivitiesApi';
export * from './managementAPIsAuthenticationsPerApplicationApi';
import { ManagementAPIsAuthenticationsPerApplicationApi } from './managementAPIsAuthenticationsPerApplicationApi';
export * from './managementAPIsBillOfMaterialsBOMApi';
import { ManagementAPIsBillOfMaterialsBOMApi } from './managementAPIsBillOfMaterialsBOMApi';
export * from './managementAPIsBrandingBrandingSettingsApi';
import { ManagementAPIsBrandingBrandingSettingsApi } from './managementAPIsBrandingBrandingSettingsApi';
export * from './managementAPIsBrandingBrandingThemesApi';
import { ManagementAPIsBrandingBrandingThemesApi } from './managementAPIsBrandingBrandingThemesApi';
export * from './managementAPIsCapabilitiesApi';
import { ManagementAPIsCapabilitiesApi } from './managementAPIsCapabilitiesApi';
export * from './managementAPIsCertificateManagementApi';
import { ManagementAPIsCertificateManagementApi } from './managementAPIsCertificateManagementApi';
export * from './managementAPIsCustomDomainsApi';
import { ManagementAPIsCustomDomainsApi } from './managementAPIsCustomDomainsApi';
export * from './managementAPIsDeviceAuthenticationPolicyApi';
import { ManagementAPIsDeviceAuthenticationPolicyApi } from './managementAPIsDeviceAuthenticationPolicyApi';
export * from './managementAPIsEnvironmentsApi';
import { ManagementAPIsEnvironmentsApi } from './managementAPIsEnvironmentsApi';
export * from './managementAPIsGatewayManagementGatewayCredentialsApi';
import { ManagementAPIsGatewayManagementGatewayCredentialsApi } from './managementAPIsGatewayManagementGatewayCredentialsApi';
export * from './managementAPIsGatewayManagementGatewayInstancesApi';
import { ManagementAPIsGatewayManagementGatewayInstancesApi } from './managementAPIsGatewayManagementGatewayInstancesApi';
export * from './managementAPIsGatewayManagementGatewayRoleAssignmentsApi';
import { ManagementAPIsGatewayManagementGatewayRoleAssignmentsApi } from './managementAPIsGatewayManagementGatewayRoleAssignmentsApi';
export * from './managementAPIsGatewayManagementGatewaysApi';
import { ManagementAPIsGatewayManagementGatewaysApi } from './managementAPIsGatewayManagementGatewaysApi';
export * from './managementAPIsGroupsApi';
import { ManagementAPIsGroupsApi } from './managementAPIsGroupsApi';
export * from './managementAPIsIdentityPropagationProvisioningPropagationMappingsApi';
import { ManagementAPIsIdentityPropagationProvisioningPropagationMappingsApi } from './managementAPIsIdentityPropagationProvisioningPropagationMappingsApi';
export * from './managementAPIsIdentityPropagationProvisioningPropagationPlansApi';
import { ManagementAPIsIdentityPropagationProvisioningPropagationPlansApi } from './managementAPIsIdentityPropagationProvisioningPropagationPlansApi';
export * from './managementAPIsIdentityPropagationProvisioningPropagationRevisionsApi';
import { ManagementAPIsIdentityPropagationProvisioningPropagationRevisionsApi } from './managementAPIsIdentityPropagationProvisioningPropagationRevisionsApi';
export * from './managementAPIsIdentityPropagationProvisioningPropagationRulesApi';
import { ManagementAPIsIdentityPropagationProvisioningPropagationRulesApi } from './managementAPIsIdentityPropagationProvisioningPropagationRulesApi';
export * from './managementAPIsIdentityPropagationProvisioningPropagationStoreMetadataApi';
import { ManagementAPIsIdentityPropagationProvisioningPropagationStoreMetadataApi } from './managementAPIsIdentityPropagationProvisioningPropagationStoreMetadataApi';
export * from './managementAPIsIdentityPropagationProvisioningPropagationStoresApi';
import { ManagementAPIsIdentityPropagationProvisioningPropagationStoresApi } from './managementAPIsIdentityPropagationProvisioningPropagationStoresApi';
export * from './managementAPIsIdentityProviderManagementIdentityProviderAttributesApi';
import { ManagementAPIsIdentityProviderManagementIdentityProviderAttributesApi } from './managementAPIsIdentityProviderManagementIdentityProviderAttributesApi';
export * from './managementAPIsIdentityProviderManagementIdentityProvidersApi';
import { ManagementAPIsIdentityProviderManagementIdentityProvidersApi } from './managementAPIsIdentityProviderManagementIdentityProvidersApi';
export * from './managementAPIsImagesApi';
import { ManagementAPIsImagesApi } from './managementAPIsImagesApi';
export * from './managementAPIsIntegrationCatalogApi';
import { ManagementAPIsIntegrationCatalogApi } from './managementAPIsIntegrationCatalogApi';
export * from './managementAPIsLanguageManagementLanguageLocalizationStatusApi';
import { ManagementAPIsLanguageManagementLanguageLocalizationStatusApi } from './managementAPIsLanguageManagementLanguageLocalizationStatusApi';
export * from './managementAPIsLanguageManagementLanguagesApi';
import { ManagementAPIsLanguageManagementLanguagesApi } from './managementAPIsLanguageManagementLanguagesApi';
export * from './managementAPIsLicensesApi';
import { ManagementAPIsLicensesApi } from './managementAPIsLicensesApi';
export * from './managementAPIsMFASettingsApi';
import { ManagementAPIsMFASettingsApi } from './managementAPIsMFASettingsApi';
export * from './managementAPIsNotificationsNotificationsSettingsApi';
import { ManagementAPIsNotificationsNotificationsSettingsApi } from './managementAPIsNotificationsNotificationsSettingsApi';
export * from './managementAPIsNotificationsNotificationsSettingsSMTPApi';
import { ManagementAPIsNotificationsNotificationsSettingsSMTPApi } from './managementAPIsNotificationsNotificationsSettingsSMTPApi';
export * from './managementAPIsNotificationsNotificationsTemplatesApi';
import { ManagementAPIsNotificationsNotificationsTemplatesApi } from './managementAPIsNotificationsNotificationsTemplatesApi';
export * from './managementAPIsNotificationsPhoneDeliverySettingsApi';
import { ManagementAPIsNotificationsPhoneDeliverySettingsApi } from './managementAPIsNotificationsPhoneDeliverySettingsApi';
export * from './managementAPIsNotificationsTrustedEmailAddressesApi';
import { ManagementAPIsNotificationsTrustedEmailAddressesApi } from './managementAPIsNotificationsTrustedEmailAddressesApi';
export * from './managementAPIsNotificationsTrustedEmailDomainsApi';
import { ManagementAPIsNotificationsTrustedEmailDomainsApi } from './managementAPIsNotificationsTrustedEmailDomainsApi';
export * from './managementAPIsOrganizationsApi';
import { ManagementAPIsOrganizationsApi } from './managementAPIsOrganizationsApi';
export * from './managementAPIsPasswordPoliciesApi';
import { ManagementAPIsPasswordPoliciesApi } from './managementAPIsPasswordPoliciesApi';
export * from './managementAPIsPopulationsApi';
import { ManagementAPIsPopulationsApi } from './managementAPIsPopulationsApi';
export * from './managementAPIsResourcesResourceAttributesApi';
import { ManagementAPIsResourcesResourceAttributesApi } from './managementAPIsResourcesResourceAttributesApi';
export * from './managementAPIsResourcesResourceScopesApi';
import { ManagementAPIsResourcesResourceScopesApi } from './managementAPIsResourcesResourceScopesApi';
export * from './managementAPIsResourcesResourcesApi';
import { ManagementAPIsResourcesResourcesApi } from './managementAPIsResourcesResourcesApi';
export * from './managementAPIsRiskManagementRiskAdvancedPredictorsApi';
import { ManagementAPIsRiskManagementRiskAdvancedPredictorsApi } from './managementAPIsRiskManagementRiskAdvancedPredictorsApi';
export * from './managementAPIsRiskManagementRiskEvaluationsApi';
import { ManagementAPIsRiskManagementRiskEvaluationsApi } from './managementAPIsRiskManagementRiskEvaluationsApi';
export * from './managementAPIsRiskManagementRiskPoliciesApi';
import { ManagementAPIsRiskManagementRiskPoliciesApi } from './managementAPIsRiskManagementRiskPoliciesApi';
export * from './managementAPIsRolesApi';
import { ManagementAPIsRolesApi } from './managementAPIsRolesApi';
export * from './managementAPIsSchemasApi';
import { ManagementAPIsSchemasApi } from './managementAPIsSchemasApi';
export * from './managementAPIsSignOnPoliciesSignOnPoliciesApi';
import { ManagementAPIsSignOnPoliciesSignOnPoliciesApi } from './managementAPIsSignOnPoliciesSignOnPoliciesApi';
export * from './managementAPIsSignOnPoliciesSignOnPolicyActionsApi';
import { ManagementAPIsSignOnPoliciesSignOnPolicyActionsApi } from './managementAPIsSignOnPoliciesSignOnPolicyActionsApi';
export * from './managementAPIsSubscriptionsWebhooksApi';
import { ManagementAPIsSubscriptionsWebhooksApi } from './managementAPIsSubscriptionsWebhooksApi';
export * from './managementAPIsTotalIdentitiesApi';
import { ManagementAPIsTotalIdentitiesApi } from './managementAPIsTotalIdentitiesApi';
export * from './managementAPIsUserActivitiesApi';
import { ManagementAPIsUserActivitiesApi } from './managementAPIsUserActivitiesApi';
export * from './managementAPIsUsersEnableUsersApi';
import { ManagementAPIsUsersEnableUsersApi } from './managementAPIsUsersEnableUsersApi';
export * from './managementAPIsUsersEnableUsersMFAApi';
import { ManagementAPIsUsersEnableUsersMFAApi } from './managementAPIsUsersEnableUsersMFAApi';
export * from './managementAPIsUsersGroupMembershipApi';
import { ManagementAPIsUsersGroupMembershipApi } from './managementAPIsUsersGroupMembershipApi';
export * from './managementAPIsUsersLinkedAccountsApi';
import { ManagementAPIsUsersLinkedAccountsApi } from './managementAPIsUsersLinkedAccountsApi';
export * from './managementAPIsUsersMFADevicesApi';
import { ManagementAPIsUsersMFADevicesApi } from './managementAPIsUsersMFADevicesApi';
export * from './managementAPIsUsersMFAPairingKeysApi';
import { ManagementAPIsUsersMFAPairingKeysApi } from './managementAPIsUsersMFAPairingKeysApi';
export * from './managementAPIsUsersSessionsApi';
import { ManagementAPIsUsersSessionsApi } from './managementAPIsUsersSessionsApi';
export * from './managementAPIsUsersUserAccountsApi';
import { ManagementAPIsUsersUserAccountsApi } from './managementAPIsUsersUserAccountsApi';
export * from './managementAPIsUsersUserAgreementConsentsApi';
import { ManagementAPIsUsersUserAgreementConsentsApi } from './managementAPIsUsersUserAgreementConsentsApi';
export * from './managementAPIsUsersUserIDVerificationApi';
import { ManagementAPIsUsersUserIDVerificationApi } from './managementAPIsUsersUserIDVerificationApi';
export * from './managementAPIsUsersUserPasswordsApi';
import { ManagementAPIsUsersUserPasswordsApi } from './managementAPIsUsersUserPasswordsApi';
export * from './managementAPIsUsersUserPopulationsApi';
import { ManagementAPIsUsersUserPopulationsApi } from './managementAPIsUsersUserPopulationsApi';
export * from './managementAPIsUsersUserRoleAssignmentsApi';
import { ManagementAPIsUsersUserRoleAssignmentsApi } from './managementAPIsUsersUserRoleAssignmentsApi';
export * from './managementAPIsUsersUsersApi';
import { ManagementAPIsUsersUsersApi } from './managementAPIsUsersUsersApi';
import * as http from 'http';

export class HttpError extends Error {
    constructor (public response: http.IncomingMessage, public body: any, public statusCode?: number) {
        super('HTTP request failed');
        this.name = 'HttpError';
    }
}

export { RequestFile } from '../model/models';

export const APIS = [ManagementAPIsActiveIdentityCountsApi, ManagementAPIsAgreementManagementAgreementLanguagesResourcesApi, ManagementAPIsAgreementManagementAgreementRevisionsResourcesApi, ManagementAPIsAgreementManagementAgreementsResourcesApi, ManagementAPIsAlertingApi, ManagementAPIsApplicationsApplicationAttributeMappingApi, ManagementAPIsApplicationsApplicationMFAPushCredentialsApi, ManagementAPIsApplicationsApplicationResourceGrantsApi, ManagementAPIsApplicationsApplicationRoleAssignmentsApi, ManagementAPIsApplicationsApplicationSecretApi, ManagementAPIsApplicationsApplicationSignOnPolicyAssignmentsApi, ManagementAPIsApplicationsApplicationsApi, ManagementAPIsAuditActivitiesApi, ManagementAPIsAuthenticationsPerApplicationApi, ManagementAPIsBillOfMaterialsBOMApi, ManagementAPIsBrandingBrandingSettingsApi, ManagementAPIsBrandingBrandingThemesApi, ManagementAPIsCapabilitiesApi, ManagementAPIsCertificateManagementApi, ManagementAPIsCustomDomainsApi, ManagementAPIsDeviceAuthenticationPolicyApi, ManagementAPIsEnvironmentsApi, ManagementAPIsGatewayManagementGatewayCredentialsApi, ManagementAPIsGatewayManagementGatewayInstancesApi, ManagementAPIsGatewayManagementGatewayRoleAssignmentsApi, ManagementAPIsGatewayManagementGatewaysApi, ManagementAPIsGroupsApi, ManagementAPIsIdentityPropagationProvisioningPropagationMappingsApi, ManagementAPIsIdentityPropagationProvisioningPropagationPlansApi, ManagementAPIsIdentityPropagationProvisioningPropagationRevisionsApi, ManagementAPIsIdentityPropagationProvisioningPropagationRulesApi, ManagementAPIsIdentityPropagationProvisioningPropagationStoreMetadataApi, ManagementAPIsIdentityPropagationProvisioningPropagationStoresApi, ManagementAPIsIdentityProviderManagementIdentityProviderAttributesApi, ManagementAPIsIdentityProviderManagementIdentityProvidersApi, ManagementAPIsImagesApi, ManagementAPIsIntegrationCatalogApi, ManagementAPIsLanguageManagementLanguageLocalizationStatusApi, ManagementAPIsLanguageManagementLanguagesApi, ManagementAPIsLicensesApi, ManagementAPIsMFASettingsApi, ManagementAPIsNotificationsNotificationsSettingsApi, ManagementAPIsNotificationsNotificationsSettingsSMTPApi, ManagementAPIsNotificationsNotificationsTemplatesApi, ManagementAPIsNotificationsPhoneDeliverySettingsApi, ManagementAPIsNotificationsTrustedEmailAddressesApi, ManagementAPIsNotificationsTrustedEmailDomainsApi, ManagementAPIsOrganizationsApi, ManagementAPIsPasswordPoliciesApi, ManagementAPIsPopulationsApi, ManagementAPIsResourcesResourceAttributesApi, ManagementAPIsResourcesResourceScopesApi, ManagementAPIsResourcesResourcesApi, ManagementAPIsRiskManagementRiskAdvancedPredictorsApi, ManagementAPIsRiskManagementRiskEvaluationsApi, ManagementAPIsRiskManagementRiskPoliciesApi, ManagementAPIsRolesApi, ManagementAPIsSchemasApi, ManagementAPIsSignOnPoliciesSignOnPoliciesApi, ManagementAPIsSignOnPoliciesSignOnPolicyActionsApi, ManagementAPIsSubscriptionsWebhooksApi, ManagementAPIsTotalIdentitiesApi, ManagementAPIsUserActivitiesApi, ManagementAPIsUsersEnableUsersApi, ManagementAPIsUsersEnableUsersMFAApi, ManagementAPIsUsersGroupMembershipApi, ManagementAPIsUsersLinkedAccountsApi, ManagementAPIsUsersMFADevicesApi, ManagementAPIsUsersMFAPairingKeysApi, ManagementAPIsUsersSessionsApi, ManagementAPIsUsersUserAccountsApi, ManagementAPIsUsersUserAgreementConsentsApi, ManagementAPIsUsersUserIDVerificationApi, ManagementAPIsUsersUserPasswordsApi, ManagementAPIsUsersUserPopulationsApi, ManagementAPIsUsersUserRoleAssignmentsApi, ManagementAPIsUsersUsersApi];
